name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Thank you for your pull request. However, you have submitted this PR on the HyperfComponent organization which is a read-only sub split of `hyperf-component/components`. Please submit your PR on the https://github.com/hyperf-component/components repository.<br><br>Thanks!"
